const posts = [
    "https://jaikvik.in/lab/new-post-video/post/ancoustic-nest-pet-panel-1.jpg",
    "https://jaikvik.in/lab/new-post-video/post/uni-spares.jpg",
    "https://jaikvik.in/lab/new-post-video/post/ambrosia-beekeeping-academy-2.jpg",
    "https://jaikvik.in/lab/new-post-video/post/anaansh.jpg",
    "https://jaikvik.in/lab/new-post-video/post/anp-bee-1.jpg",
    "https://jaikvik.in/lab/new-post-video/post/atlas-rolling-1.jpg",
    "https://jaikvik.in/lab/new-post-video/post/bweld.jpg",
    "https://jaikvik.in/lab/new-post-video/post/celestial.jpeg",
    "https://jaikvik.in/lab/new-post-video/post/cmed.jpg",
    "https://jaikvik.in/lab/new-post-video/post/comfort-2.jpg",
    "https://jaikvik.in/lab/new-post-video/post/dicocon-gel-25.jpg",
    "https://jaikvik.in/lab/new-post-video/post/gutaderme.jpeg",
    "https://jaikvik.in/lab/new-post-video/post/envirotech-1.jpg",
    "https://jaikvik.in/lab/new-post-video/post/felicity.jpeg",
    "https://jaikvik.in/lab/new-post-video/post/galaxy.jpg",
    "https://jaikvik.in/lab/new-post-video/post/ganesh-sky-balloon.jpg",
    "https://jaikvik.in/lab/new-post-video/post/gemak.jpg",
    "https://jaikvik.in/lab/new-post-video/post/glow-green.jpg",
    "https://jaikvik.in/lab/new-post-video/post/indian-roller.jpg",
    "https://jaikvik.in/lab/new-post-video/post/gemak-2.jpg",
    "https://jaikvik.in/lab/new-post-video/post/micro-industry.jpg",
    "https://jaikvik.in/lab/new-post-video/post/my-brand-please.jpeg",
    "https://jaikvik.in/lab/new-post-video/post/nexus.jpg",
    "https://jaikvik.in/lab/new-post-video/post/poly-pack.jpg",
    "https://jaikvik.in/lab/new-post-video/post/radicon.jpg",
    "https://jaikvik.in/lab/new-post-video/post/refer-me.jpg",
    "https://jaikvik.in/lab/new-post-video/post/regent.jpg",
    "https://jaikvik.in/lab/new-post-video/post/shree-ram-2.jpg",
    "https://jaikvik.in/lab/new-post-video/post/smd-1.jpg",
    "https://jaikvik.in/lab/new-post-video/post/sports-barrel.jpg",
    "https://jaikvik.in/lab/new-post-video/post/uni-spares-2.jpg"
];

export default posts;