import type blogInterface from "../interfaces/blogInterface";

// Blog data array
const blogs: blogInterface[] = [
    {
        id: 1,
        category: 'Social Media Marketing',
        author: 'Dixit Mishra',
        date: '10 Jan 2025',
        title: 'Unlocking Growth with Instagram Reels in 2025',
        description: 'Instagram Reels are dominating social media. Learn how to leverage them for brand visibility...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 2,
        category: 'SEO',
        author: 'Dixit Mishra',
        date: '15 Jan 2025',
        title: 'Top SEO Trends to Watch in 2025',
        description: 'Stay ahead with the latest SEO strategies shaping search engine rankings this year...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 3,
        category: 'Website Development',
        author: 'Dixit Mishra',
        date: '20 Jan 2025',
        title: 'Why Progressive Web Apps Are the Future',
        description: 'Explore how PWAs enhance user experience and boost business performance...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/web.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 4,
        category: 'PPC Advertising',
        author: 'Dixit Mishra',
        date: '25 Jan 2025',
        title: 'Advanced PPC Techniques for Maximum ROI',
        description: 'Master the art of Pay-Per-Click with cutting-edge strategies for 2025...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/ppc.jpg',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 5,
        category: 'Content Marketing',
        author: 'Dixit Mishra',
        date: '01 Feb 2025',
        title: 'How to Create Content That Converts',
        description: 'Turn readers into customers with compelling content strategies...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 6,
        category: 'Social Media Marketing',
        author: 'Dixit Mishra',
        date: '05 Feb 2025',
        title: 'Building a Loyal Audience on LinkedIn',
        description: 'Unlock LinkedIn’s potential to grow your professional network and brand...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 7,
        category: 'E-Commerce SEO',
        author: 'Dixit Mishra',
        date: '10 Feb 2025',
        title: 'The Ultimate Guide to E-Commerce SEO Success',
        description: 'Boost online sales with SEO tactics tailored for e-commerce platforms...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/The Ultimate guide.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 8,
        category: 'SEO',
        author: 'Dixit Mishra',
        date: '15 Feb 2025',
        title: 'How Voice Search is Changing SEO',
        description: 'Adapt your SEO strategy for the rise of voice-activated devices...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/why.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 9,
        category: 'Digital Marketing',
        author: 'Dixit Mishra',
        date: '20 Feb 2025',
        title: 'AI in Digital Marketing: The Next Big Thing',
        description: 'Discover how AI tools are revolutionizing ad targeting and customer engagement...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 10,
        category: 'Email Marketing',
        author: 'Dixit Mishra',
        date: '25 Feb 2025',
        title: 'Personalized Emails: Boosting Open Rates',
        description: 'Learn how personalization can transform your email marketing campaigns...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 11,
        category: 'Analytics',
        author: 'Dixit Mishra',
        date: '01 Mar 2025',
        title: 'Using Google Analytics for Smarter Decisions',
        description: 'Unlock insights from your data to refine your marketing strategy...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 12,
        category: 'Branding',
        author: 'Dixit Mishra',
        date: '05 Mar 2025',
        title: 'Building a Strong Brand Identity Online',
        description: 'Create a lasting impression with a cohesive digital brand presence...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 13,
        category: 'Video Marketing',
        author: 'Dixit Mishra',
        date: '10 Mar 2025',
        title: 'Why Video Content is King in 2025',
        description: 'Engage audiences with powerful video marketing strategies...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 14,
        category: 'Local SEO',
        author: 'Dixit Mishra',
        date: '15 Mar 2025',
        title: 'Winning Local Customers with SEO',
        description: 'Dominate your local market with targeted SEO techniques...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 15,
        category: 'Influencer Marketing',
        author: 'Dixit Mishra',
        date: '20 Mar 2025',
        title: 'Choosing the Right Influencers for Your Brand',
        description: 'Maximize ROI by partnering with influencers who align with your goals...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 16,
        category: 'Social Media Marketing',
        author: 'Dixit Mishra',
        date: '25 Mar 2025',
        title: 'Mastering TikTok Ads for Business Growth',
        description: 'Tap into TikTok’s massive audience with effective ad campaigns...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 17,
        category: 'SEO',
        author: 'Dixit Mishra',
        date: '01 Apr 2025',
        title: 'Link Building Strategies That Work in 2025',
        description: 'Boost your site’s authority with modern link-building tactics...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 18,
        category: 'Website Development',
        author: 'Dixit Mishra',
        date: '05 Apr 2025',
        title: 'Speed Optimization for Better User Experience',
        description: 'Learn why site speed matters and how to optimize it effectively...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/web.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 19,
        category: 'PPC Advertising',
        author: 'Dixit Mishra',
        date: '10 Apr 2025',
        title: 'Retargeting Ads: Winning Back Lost Customers',
        description: 'Re-engage visitors with smart PPC retargeting strategies...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/ppc.jpg',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 20,
        category: 'Content Marketing',
        author: 'Dixit Mishra',
        date: '15 Apr 2025',
        title: 'Evergreen Content: A Long-Term Strategy',
        description: 'Create timeless content that drives traffic year after year...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 21,
        category: 'Digital Marketing',
        author: 'Dixit Mishra',
        date: '20 Apr 2025',
        title: 'The Power of User-Generated Content',
        description: 'Leverage customer content to build trust and authenticity...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 22,
        category: 'SEO',
        author: 'Dixit Mishra',
        date: '25 Apr 2025',
        title: 'Mobile-First Indexing: What You Need to Know',
        description: 'Optimize your site for Google’s mobile-first approach...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 23,
        category: 'Social Media Marketing',
        author: 'Dixit Mishra',
        date: '01 May 2025',
        title: 'Creating Viral Campaigns on Twitter',
        description: 'Craft tweets that resonate and spread like wildfire...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 24,
        category: 'Email Marketing',
        author: 'Dixit Mishra',
        date: '05 May 2025',
        title: 'Segmentation Secrets for Email Success',
        description: 'Target the right audience with tailored email lists...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
    {
        id: 25,
        category: 'Analytics',
        author: 'Dixit Mishra',
        date: '10 May 2025',
        title: 'Tracking ROI with Advanced Analytics Tools',
        description: 'Measure your marketing success with the latest analytics platforms...',
        image: 'https://jaikvik.in/lab/new-post-video/img/blog/blog.png',
        link: 'how-can-i-become-an-expert-in-ppc-advertising.php',
    },
];

export default blogs;